### ISSUE TITLE
Cypress ^7.4.0 as dependency causes downloading multiple cypress version when used with Cypress in other version

### ISSUE THREAD

**Issue by TomaszG** [annaet/cypress-tags#100]
When I want to use cypress-tags with e.g. Cypress 8, then `npm i` downloads Cypress 8 (as it's my dev dependency) and Cypress 7.4.0 (as it's a cypress-tags dependency). Of course, Cypress 7.4.0 is not used at all, and due to the size of the Cypress package downloading it takes a significant amount of time. Proposed solution is to include Cypress as a peer dependency, preferably in `any` version.
```json
      "peerDependencies": {
        "cypress": "*"
      }
```

**Comment by TomaszG** [comment]
@annaet were you able to take a look at this?

**Comment by annaet** [comment]
@TomaszG I've added a comment to your pull request.
