### ISSUE TITLE
Does cypress-tags work only with relative paths from the current package? 

### ISSUE THREAD

**Issue by MaksimYaginov** [annaet/cypress-tags#102]
Hi! When I use a path relative to root (cypress/utils/dataGenerator)-  Can't walk dependency graph: Cannot find module 'cypress/pages/mainPage', but I use a path relative from current package (../../../utils/dataGenerator) - it works.
How can I solve this?

**Comment by annaet** [comment]
Hi @MaksimYaginov 

This doesn't sound like an issue with the cypress-tags plugin, rather a problem with your app itself? I'm not sure why you would be using a path relative to root rather than a path relative to the current file when importing data.
