### ISSUE TITLE
Does cypress-tags work if your Cypress code is not written in TypeScript?

### ISSUE THREAD

**Issue by rightsaidjames** [annaet/cypress-tags#116]
Apologies if this isn't the right forum for idle questions - let me know if you'd prefer a different medium.

I was wondering if it's possible to use the cypress-tags plugin if your project is already using TypeScript for other stuff (i.e. the actual frontend code) but the Cypress code is written in vanilla JS? We already have a dedicated tsconfig.json for our Cypress codebase ([like this one](https://github.com/rightsaidjames/cypress-starter-kit/blob/main/tests/cypress/tsconfig.json)), but its current purpose is to enable Intellisense/code completion/linting - it doesn't output anything.

Do you know if this use case is viable?

**Comment by TomaszG** [comment]
That's the case in my project:
1. Cypress tests are in JS.
2. Tags definitions for cypress-tags are in TS.
2. Backend code (parts of it are used in Cypress) is in TS, previously it was a mix of JS and TS.

Everything works fine as Cypress supports both JS and TS - `cypress open` and `cypress run` commands don't have any problem running the tests in such form.

**Comment by annaet** [comment]
Hi @rightsaidjames

As @TomaszG says it should be possible to write your tests in vanilla JS, cypress-tags uses typescript to filter your tests based on their tags, but it should not prevent you from writing the tests in pure JS.

**Comment by rightsaidjames** [comment]
Thanks both for your helpful and quick responses 🙂
