### ISSUE TITLE
CYPRESS_INCLUDE_TAGS is not a recognized as an internal or external command error.

### ISSUE THREAD

**Issue by jinisha** [annaet/cypress-tags#129]
![image](https://user-images.githubusercontent.com/9576963/140572129-435c788c-c8ee-4edc-a9b7-c78520bf0cd5.png)

**Comment by annaet** [comment]
Hi @jinisha 

It looks like you're running this on a windows command line, is that right? If so this run command will fail as it sets environment variables differently.

I believe you'd need to add a `set` in front of the env vars for them to set correctly. So the command would become:

```
set CYPRESS_INCLUDE_TAGS=smoke cypress run
```

Hopefully this helps.

**Comment by jinisha** [comment]
In the 1st instance I am running the npm run cy:smoke command after downloading the working example. It threw CYPRESS_INCLUDE_TAGS is not reccognized as an internal command.

In the 2nd instance, I tried passing Cypress environment variables in the package.json and its working as expected.
![image](https://user-images.githubusercontent.com/9576963/140972584-784a0d2a-6954-4565-8469-7a2583c0d34b.png)

**Comment by annaet** [comment]
@jinisha Great, glad to see you got it working. 

I will make note of the fact that env vars need to be set this way for Windows users thank you.

Given you have resolved the issue, I will close this ticket.
