### ISSUE TITLE
Open Cypress with tags

### ISSUE THREAD

**Issue by iTsFILIPOficial** [annaet/cypress-tags#14]
Im new to cypress tag, but I was looking around and was wondering if is possible to have the cypress open command that will only display the files that follow the tags.

**Comment by annaet** [comment]
@iTsFILIPOficial You can use the environment variables in the command line to control what's shown in the Cypress console.

Eg. `CYPRESS_INCLUDE_TAGS=WIP npx cypress open`

**Comment by cw-pragna-bandi** [comment]
Hey @annaet , this command does not seem to filter out files according to different tags. It is still showing me all the files.

**Comment by eshaparenko** [comment]
have the same issue
