### ISSUE TITLE
MaxListenersExceededWarning warning

### ISSUE THREAD

**Issue by clarkd** [annaet/cypress-tags#15]
We are seeing the following error when using this plugin, any tips to avoid this? It's failing our CI/CD tests as it's flagged as an error.

(node:1580) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 preprocessor:close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit

**Comment by annaet** [comment]
@clarkd I haven't seen this issue myself, but looks like it could be something coming from Cypress itself?

Have you checked out this issue?
https://github.com/cypress-io/cypress/issues/1305

**Comment by clarkd** [comment]
@annaet Thanks, I had seen that issue & having dug into it a bit further, I can confirm the error isn't related to this plugin. Closing!
