### ISSUE TITLE
Adding support for boolean expressions

### ISSUE THREAD

**Issue by anudeepreddy** [annaet/cypress-tags#166]
Hi @annaet👋,

Thanks for the work you have done on this. I am planning to add support for boolean expressions in parallel to the comma-separated tags that are already supported. With this feature users will be able to provide a config like `CYPRESS_INCLUDE_EXPRESSION='smoke AND (my-feature1 OR my-feature2)'`. This ability will let users slice the tests more effectively.

I will be adding two more env config variables:
- CYPRESS_INCLUDE_EXPRESSION
- CYPRESS_EXCLUDE_EXPRESSION
- USE_INCLUDE_EXCLUDE_EXPRESSIONS

Please let me know what you think of this proposal and also if there is anything that I have to keep in mind before making any change.

Thanks

**Comment by annaet** [comment]
Hi @anudeepreddy 

That sounds great, thanks for the suggestion. The contribution would be welcome.

**Comment by annaet** [comment]
Available in v1.0.0 now. Thanks for your contribution!
