### ISSUE TITLE
Use cypress-tags with cy2 for parallel testing

### ISSUE THREAD

**Issue by jmgate** [annaet/cypress-tags#187]
I need to be able to use `cypress-tags` in conjunction with the [`cy2` executable](https://docs.sorry-cypress.dev/cypress-agent/cy2) provided with [Sorry Cypress](https://sorry-cypress.dev/) to achieve test parallelization.  Is there a way to have `cypress-tags` use `cy2` instead of `cypress` under the hood?

**Comment by annaet** [comment]
Hi,

I've not used sorry cypress myself so I'm not sure how their plugin interactions work. You would likely be able to adapt the cypress-tags code to work with it but I doubt it'll just plugin out of the box.

**Comment by jmgate** [comment]
We managed to get it working, and there weren't any hacks needed with respect to `cypress-tags`.  Apparently our problem was just in how we had `cy2` listed as a dependency of our Cypress tests package.  Sorry to have bothered you.
