### ISSUE TITLE
Adding to specified test .only or .skip  to the function not working with tags

### ISSUE THREAD

**Issue by nalmabrcom** [annaet/cypress-tags#19]
Hello,

seems that having a tag and at the same time `.only` or `.skip` (e.g., `describe.only(['smoke'],'TC174956 Copybook - not exist: error underlined', () => {` brings this error:
```
TypeError: The following error originated from your test code, not from Cypress.

  > Suite argument "title" must be a string. Received type "object"

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
```

**Comment by annaet** [comment]
Hi @nalmabrcom 

Thanks for raising this issue. This should be fixed in the latest release `v0.0.21`. Please try this out and let me know if you have anymore issues with this.
