### ISSUE TITLE
sync skip abort execution issue with cypress-tags

### ISSUE THREAD

**Issue by gogoid88** [annaet/cypress-tags#203]
The issue seems to be config-related not code related. The repo is private and protected so won't be able to share it.

Running - > "npx cypress-tags run -e 'TAGS=https://github.com/rerun' --headless" command with configuration below works fine.
Cypress package version: 9.5.1
Cypress binary version: 9.5.1
Electron version: 15.3.4
Bundled Node version:
16.5.0

But running the same command with the below configuration gives the error "sync skip - aborting execution"
Most probably an issue with the binary version of 6.0.1. Can you please check this? I narrowed it down.

Cypress package version: 9.5.3
Cypress binary version: 6.0.1
Electron version: 11.0.2
Bundled Node version:
12.18.6

**Comment by gogoid88** [comment]
Can someone please check this issue. 

Additionally if the tag is present in multiple feature files then cypress executes only one feature file.

**Comment by annaet** [comment]
Hi @gogoid88 

This does not sound like an issue with the `cypress-tags` preprocessor. 

However I would suggest using the same version of the cypress binary as your cypress package.
