### ISSUE TITLE
V1.0.0 not compatible with cypress 9

### ISSUE THREAD

**Issue by anudeepreddy** [annaet/cypress-tags#216]
Hi,

I have just noticed that the support for cypress 10 breaks the plugin's compatibility with versions below that, is this an intended change to not support older versions of cypress?

**Comment by annaet** [comment]
Hi @anudeepreddy,

Nothing has changed in the functionality with the move to Cypress 10, so if you're still using a lower version of Cypress you should be able to stay on your previous version of cypress-tags

**Comment by anudeepreddy** [comment]
For version 1.0.0 the peer dependency of Cypress is >=10. I am currently using version 9 of Cypress and I am unable to use cypress-tags@1.0.0 which has support for expressions.

**Comment by annaet** [comment]
Ah I see, good point. I will take a look at including support for lower versions given that.

**Comment by gebeto** [comment]
Yeah, I'm also using NX v13, and there are only max version of cypress supported is v8, but I had also installed cypress v6 and it works fine with so old version, can you please allow this plugin also for v6?

**Comment by annaet** [comment]
Hi @anudeepreddy / @gebeto

I have just released v1.1.0 with support for v6. Hopefully this fixes your issue.

**Comment by gebeto** [comment]
Thanks a lot! 🙌
