### ISSUE TITLE
Tests tagged in it() are not run if describe() is also tagged but with a different tag.

### ISSUE THREAD

**Issue by TomaszG** [annaet/cypress-tags#25]
I'm not sure if that's a bug, however, I was surprised when my tests were not run despite the fact they have a correct tag set.

This can be easily reproduced with cypress-tags-example repo: https://github.com/annaet/cypress-tags-example

1. Clone and run `npm i`
2. Run `CYPRESS_INCLUDE_TAGS=FEATURE npx cypress run`
3. Check if `it([Tag.FEATURE], 'I will also become a wip test', () => { })` from `enum.spec.js` has been run.

The expected result in my understanding is that test should be run, however, it isn't because the whole `describe` is tagged as `WIP` (but WIP wasn't excluded so it shouldn't matter).

**Comment by annaet** [comment]
Hi @TomaszG 

Thanks for your comment, and I think you're right!

It was originally planned that if a test was tagged but **wasn't** tagged with the requested tag, it would get ignored. Then I duplicated this functionality for describe blocks without much thought about the interaction between them.

Your point that we're not ignoring `WIP` tags in your example means that the tag at the describe block level should be ignored, and fall to the individual test tags instead.

This is still quite a new project, so thanks for raising this issue! I'll let you know when I get this fixed and a new version released.

**Comment by annaet** [comment]
Hi @TomaszG I've just release v0.1.0 of cypress-tags. I believe this version should fix your issue.

Please let me know if you're still experiencing any issues after upgrading.
