### ISSUE TITLE
unable to run all tags 

### ISSUE THREAD

**Issue by cw-manjugawde** [annaet/cypress-tags#32]
we want to run all tags present in project, but there is no command to run it.
@annaet

**Comment by annaet** [comment]
Hi @cw-manjugawde 

You can use the environment variables `CYPRESS_INCLUDE_TAGS` and `CYPRESS_EXCLUDE_TAGS` to control which tags will be run. If you want to run all tests, whether they have tags or not, you can exclude both of these env vars.

**Comment by TomaszG** [comment]
My observation is that when you provide neither CYPRESS_INCLUDE_TAGS nor CYPRESS_EXCLUDE_TAGS then all tests are run. 

You can also operate on those envs in plugins/index.js, e.g.:
```js
// plugins/index.js
const tagify = require('cypress-tags');

const { Tags } = require('../support/tags');

// run all tags when CYPRESS_INCLUDE_TAGS='ALL' is provided
const setupTags = config => {
  if (process.env.CYPRESS_INCLUDE_TAGS.toLowerCase() === 'all') {
    config.env.CYPRESS_INCLUDE_TAGS = Object.keys(Tags)
      .map(key => Tags[key])
      .filter(value => typeof value === 'string')
      .join(',');
  }
}

module.exports = (on, config) => {
  setupTags(config);
  on('file:preprocessor', tagify(config));
  return config;
};
```
which should run all tags when 'all' is provided.

**Comment by annaet** [comment]
I'm going to close this issue as I believe it's functioning as expected.

**Comment by QuentinFarizon** [comment]
When I don't provide CYPRESS_INCLUDE_TAGS nor CYPRESS_EXCLUDE_TAGS, then NO tests are run.

What am I missing ?

**Comment by annaet** [comment]
@QuentinFarizon What command are you using to run your tests? You should be able to run your tests using the same command you would without the plugin installed, eg. `npx cypress run`

**Comment by QuentinFarizon** [comment]
Yes, simply with run

I have just installed the plugin, loaded the plugin as mentioned in the
doc, tagged one test, and ran the same I command I always ran.

Le mar. 20 juil. 2021, 23:33, Anna Thomas ***@***.***> a
écrit :
