### ISSUE TITLE
Support for running spec files not having tags

### ISSUE THREAD

**Issue by cw-pragna-bandi** [annaet/cypress-tags#33]
I have just started using this plugin and I would say it is very helpful. However, I am stuck at following -
There are certain test cases that do not have tags and I am unable to run them.
1. Is there any feature/command that will help me run my tests without any tags in it.
2. Is there any feature/command that will help me run all tests irrespective of tags.
@annaet

**Comment by annaet** [comment]
Hi @cw-pragna-bandi 

All tests will be run if you do not supply either of the environment variables. So you should just be able to run your usual test command, eg. `cypress run`.

**Comment by annaet** [comment]
Also if you wanted to run **only** the tests which don't have any tags you would currently have to exclude all your tags using the `CYPRESS_EXCLUDE_TAGS` environment variable.

**Comment by TomaszG** [comment]
It's related to https://github.com/annaet/cypress-tags/issues/32 and the answer is very similar - you can add the behavior in plugins file:
```js
// plugins/index.js
const tagify = require('cypress-tags');

const { Tags } = require('../support/tags');

// exclude all tags when CYPRESS_INCLUDE_TAGS=none or CYPRESS_EXCLUDE_TAGS=all is provided
const setupTags = config => {
  if (
    process.env.CYPRESS_INCLUDE_TAGS.toLowerCase() === 'none'
    || process.env.CYPRESS_EXCLUDE_TAGS.toLowerCase() === 'all'
  ) {
    // exclude all tags
    config.env.CYPRESS_EXCLUDE_TAGS = Object.keys(Tags)
      .map(key => Tags[key])
      .filter(value => typeof value === 'string')
      .join(',');
  }
}

module.exports = (on, config) => {
  setupTags(config);
  on('file:preprocessor', tagify(config));
  return config;
};
```

**Comment by annaet** [comment]
I'm going to close this issue as I believe the question has been answered.
