### ISSUE TITLE
Tests using xit instead of it are failing

### ISSUE THREAD

**Issue by facundoem94** [annaet/cypress-tags#47]
**Description**
Mocha command "xit" (used for skipping tests) isn't working with tags.

**Steps To Reproduce**:
1. Clone cypress-tags-example project.
2. Modify any test using "it" command with tags.
3. Run test from browser or command.

**Actual Result**:
Tests are failing using xit.

**Expected Result**:
Tests are skipped correctly using xit.

**Screenshots**:
![image](https://user-images.githubusercontent.com/16586023/117704189-f2200300-b1a0-11eb-85cc-242bd2627b09.png)
![image](https://user-images.githubusercontent.com/16586023/117704332-18de3980-b1a1-11eb-887a-35aa89649c9e.png)

**Comment by annaet** [comment]
Hi @facundoem94,

As of v0.1.0 `xit` and `xdescribe` should be supported.

Please let me know if you have any issues after upgrading.

**Comment by facundoem94** [comment]
Will take a look, thanks!

**Comment by facundoem94** [comment]
Will take a look, thanks!
