### ISSUE TITLE
Cypress Tags not working

### ISSUE THREAD

**Issue by JoxGarcia** [annaet/cypress-tags#61]
Recently was updating the new version but having these problems while I install

`npm install cypress-tags

npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

> fsevents@1.2.13 install /Users/josepablogarciapalacios/Documents/myProjects/taskeasy-2.0-testing-cy/node_modules/babel-plugin-add-module-exports/node_modules/fsevents
> node install.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 20.5.0
gyp ERR! command "/usr/local/Cellar/node/14.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/josepablogarciapalacios/Documents/myProjects/taskeasy-2.0-testing-cy/node_modules/babel-plugin-add-module-exports/node_modules/fsevents
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> fsevents@1.2.13 install /Users/josepablogarciapalacios/Documents/myProjects/taskeasy-2.0-testing-cy/node_modules/watchify/node_modules/fsevents
> node install.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 20.5.0
gyp ERR! command "/usr/local/Cellar/node/14.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/josepablogarciapalacios/Documents/myProjects/taskeasy-2.0-testing-cy/node_modules/watchify/node_modules/fsevents
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN listr2@3.10.0 requires a peer of enquirer@>= 2.3.0 < 3 but none is installed. You must install peer dependencies yourself.

+ cypress-tags@0.1.0
added 410 packages from 213 contributors and audited 747 packages in 22.634s

48 packages are looking for funding
  run `npm fund` for details

found 2 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details`
  
  
  Also when im trying to work with throws this error : 

`The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/Users/josepablogarciapalacios/Documents/myProjects/taskeasy-2.0-testing-cy/cypress/plugins/index.js`)`

MY index.js is like this:
![Screen Shot 2021-06-08 at 12 25 28](https://user-images.githubusercontent.com/74571206/121237792-a9697180-c854-11eb-9a77-0a4d4cff972f.png)

**Comment by annaet** [comment]
Hi @JoxGarcia 

I don't think this is an issue with cypress-tags, I believe it's to do with macOS updating.

See this article for details: https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d
